### ISSUE TITLE
Contribute good quality code for basic problems meant for beginners in programming

### ISSUE THREAD

**Issue by code-value** [code-value/hacktober-code#12]
* Write in any language of your choice.
* Don't add "hello world" programs. 
* Add code that adds value.
* Don't repeat code that already exists.
* Write code on your own. Do not copy.
* Well documented code is appreciated.
* Invalid PRs will be labelled "invalid"/"spam"

**Comment by rishabh15b** [comment]
can u please assign this to me?

**Comment by code-value** [comment]
> can u please assign this to me?

you can contribute

**Comment by Ankancode123** [comment]
can you please assign this to me

**Comment by wiredfoxterrier** [comment]
Hey @code-value 
I would like to contribute a few of the basic coding questions I had solved when I was getting started on Python. I would like to contribute the same to the community. It would be great if you could assign this to me.

Thanks,
Ansh Sharma
(wiredfoxterrier)

**Comment by wiredfoxterrier** [comment]
Hey @code-value 
I would also like to contribute a few basic questions I had solved when I was getting started on Java. I would like to help the community in the same. It would be great if you could assign this to me.

Thanks,
Ansh Sharma
(wiredfoxterrier)

**Comment by code-value** [comment]
> Hey @code-value
> I would also like to contribute a few basic questions I had solved when I was getting started on Java. I would like to help the community in the same. It would be great if you could assign this to me.
> 
> Thanks,
> Ansh Sharma
> (wiredfoxterrier)

feel free to contribute

**Comment by nilavya2000** [comment]
I would like to contribute to this repo.

**Comment by wiredfoxterrier** [comment]
> > Hey @code-value
> > I would also like to contribute a few basic questions I had solved when I was getting started on Java. I would like to help the community in the same. It would be great if you could assign this to me.
> > Thanks,
> > Ansh Sharma
> > (wiredfoxterrier)
> 
> feel free to contribute

I have submitted a PR. Please let me know if there are any changes required.
Thanks,
Ansh Sharma
(wiredfoxterrier)

**Comment by bhuyanamit986** [comment]
Hello @code-value 
I would like to contribute it with neural style transfer algorithm which is in python. It would be great if you assign me the task.
Thanks,
Amit Kumar Bhuyan

**Comment by Aarju02** [comment]
Hey @code-value! I have already contributed to this repo and wanted to ask you to please add a Hacktoberfest tag in this repo for this repo to count in Hacktoberfest. There was no way to contact you so, I had to write this here.

For more guidelines, please refer here: https://hacktoberfest.digitalocean.com/hacktoberfest-update

![](https://hacktoberfest-assets.nyc3.cdn.digitaloceanspaces.com/hacktoberfest-eligible-gif.gif)

**Comment by code-value** [comment]
@Aarju02 You are mistaken. I assigned him the task to arrange files in various folders based on the language in which they are written. If you want, you can add comments in your code and make a new pull request.

**Comment by code-value** [comment]
@Aarju02 refer #30

**Comment by Aarju02** [comment]
Oh, I'm so very sorry if that's the case. I actually didn't see any changes done in my files and that's why wanted to have your clarification.


It's all cool then, sorry for causing some misunderstanding.

**Comment by him9666** [comment]
can i add the batch files i prepared to schedule in windows task manager. its purpose is to shutdown the system after a particular time, by default i kept the timer to be 10 minutes. Also there is anothere batch file which cancel's the scheduled shutdown.  Please let me know if i can PR
